export const MOCK_ERR_MSG = 'MOCK_ERR_MSG';
export const MOCK_ERR_NUM_CODE = 123;
export const MOCK_ERR_ID = 'MOCK_ERR_ID';
export const MOCK_ERR_CAUSE_ERR = new Error('MOCK_ERR_CAUSE_ERR');
export const MOCK_ERR_CAUSE_STR = 'MOCK_ERR_CAUSE_STR';
export const MOCK_ERR_CODE = 'MOCK_ERR_CODE';
export const MOCK_DISPLAY_MESSAGE = 'MOCK_DISPLAY_MESSAGE';
export const MOCK_ERR_CODE_CTR_ARG = { code: MOCK_ERR_CODE };
export const MOCK_BAD_HBS = '{{MOCK_BAD_HBS}';
